spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/mng?useUnicode=TRUE&characterEncoding=UTF8&MVCC=TRUE&LOCK_TIMEOUT=10000
      password: root
      username: root
      driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8001